package com.config;

/**
 * Enum for various game phases.
 * @author Mehul
 */
public enum GameState {

	RISK_STATE_INIT,
	RISK_STATE_MAP_EDITING,
	RISK_STATE_GAMEPLAY_CREATE_PLAYERS,
	RISK_STATE_GAMEPLAY_STARTUP_PHASE,
	RISK_STATE_GAMEPLAY_REINFORCEMENT_PHASE,
	RISK_STATE_GAMEPLAY_ATTACK_PHASE,
	RISK_STATE_GAMEPLAY_FORTIFICATION_PHASE,	
}